x-container: &container
  user: "${DOCKER_UID}:${DOCKER_GID}"
  environment:
    - USER_ID=${DOCKER_UID}
    - GROUP_ID=${DOCKER_GID}
  working_dir: /workspace
    
x-cellprofiler: &cellprofiler
  <<: *container
  build:
    context: ./CellProfiler_pipeline
    dockerfile: Dockerfile
  volumes:
    - ${WORKSPACE_PATH}/CellProfiler_pipeline:/workspace
    - ${IMAGES_PATH}:/workspace_images
    - ${OUTPUT_PATH}:/output
    - ${PWD}/variables.env:/config/variables.env:ro
  working_dir: /workspace

x-cellpose: &cellpose
  <<: *container
  build:
    context: ./Cellpose_seg
    dockerfile: Dockerfile
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            capabilities: [gpu]
  shm_size: "2g"
  ipc: host
  volumes:
    - ${WORKSPACE_PATH}/Cellpose_seg:/workspace
    - ${IMAGES_PATH}:/workspace_images
    - ${OUTPUT_PATH}:/output
    - ${PWD}/variables.env:/config/variables.env:ro
  working_dir: /workspace

services:
  cellprofiler_illum:
    <<: *cellprofiler
    command: sh -c "set -xe; /workspace/Code/correct_illum.sh"

  cellpose_seg:
    <<: *cellpose
    command: sh -c "set -xe; /workspace/Code/run_cellpose.sh"
    depends_on:
      cellprofiler_illum:
        condition: service_completed_successfully

  cellprofiler_workflow:
    <<: *cellprofiler
    command: sh -c "set -xe; /workspace/Code/run_workflow.sh"
    depends_on:
      cellpose_seg:
        condition: service_completed_successfully